"""initial

Revision ID: 87e0500f2ed8
Revises: a253215c6aa6
Create Date: 2024-05-31 16:05:28.114413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e0500f2ed8'
down_revision: Union[str, None] = 'a253215c6aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userotp', 'otp',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userotp', 'otp',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###
